#!/usr/bin/env bash
# Pre-edit hook: block edits to auto-generated and managed files
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || FILE_PATH=""

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

NORMALIZED="${FILE_PATH#./}"

# Block edits to terraform-docs auto-generated module READMEs
case "$NORMALIZED" in
  terraform/website/modules/*/README.md|*/terraform/website/modules/*/README.md)
    echo "Blocked: $FILE_PATH is auto-generated by terraform-docs. Do not modify directly." >&2
    exit 2
    ;;
esac

# Block edits to detect-secrets baseline (update via: detect-secrets scan --update .secrets.baseline)
case "$NORMALIZED" in
  .secrets.baseline|*/.secrets.baseline)
    echo "Blocked: $FILE_PATH is managed by detect-secrets. Update via: detect-secrets scan --update .secrets.baseline" >&2
    exit 2
    ;;
esac

# Block edits to Terraform lock file (update via: terraform init)
case "$NORMALIZED" in
  .terraform.lock.hcl|*/.terraform.lock.hcl)
    echo "Blocked: $FILE_PATH is managed by Terraform. Update via: terraform init -upgrade" >&2
    exit 2
    ;;
esac
